language: node_js
sudo: false
node_js: stable
env:
  matrix:
  - CMD=test
  - CMD=lint
  - CMD=build
  global:
    secure: oJbjJLmJm/6wNEXxd47pXJEHJIAU5i5QdByfFfAjwKptoWlKRx+nbBhWHvg2Q67KQvm03jC+LkU6oIuHlh8WTibz+YYrz2uWm+SBmhEaXYqMY2F9Gr9/j/j2RAD3JAfQLujQPPJj8wgsjLdkLVrkQYH2Yh1nddBbxSla8mxywmY/5vVMNvxm9DjVl2ividSVH5eF7ls5A0g6MXZ/hcl2PkjYD7hYEwlRs2EKBe3M+n6VHFK/dgLXvRzzXaBWdD3pD3Vlbrmd+kWfuPSG/5V+fCf8RzdXfOyNMQBjfH2xkfXMiln/B7VVDUrUYEBGPNwllDDwKIR5x+OUDUSCVZlRNUuIAWThKaRtxovMUItXEPING3oPJO8fmYyNwUSK67nsP8Elj55CV3PtgyvZLvqg4SC22x1NGrrByDd1JjHfH7cVd4t7bn2REp16g/Z3Vys1jZ0PrMO/aNe/glBS+gypRpisuSEnwWTTeS9SKSeRwiW+uNlG+2RlA1dOiTiez1VuO3PE0HZR5+JsJf7HRBKB2cMWHr4f//20eD1HUMUGF99KVISI0WCgsJnOaabJJVKGzcxCTyREMXP3jLvaj5V8YpyFMvdqC+5/7UfyJTgw1xLpGEXdsh0LGCOV0R0gMCCaPGhLx2HWQ9doDOQxZLTTDxVfKf8G+L7JmTBfbeqLwfk=
script:
- npm run $CMD
after_success:
- echo -e "Host github.com\n\tStrictHostKeyChecking no\nIdentityFile ~/.ssh/deploy.key\n" >> ~/.ssh/config
- openssl aes-256-cbc -k "$SERVER_KEY" -in .travis/deploy_key.enc -d -a -out deploy.key
- cp deploy.key ~/.ssh/
- chmod 600 ~/.ssh/deploy.key
- '[ "$TRAVIS_BRANCH" == master ] && [ "$TRAVIS_PULL_REQUEST" == "false" ] && bash
  ./deploy.sh'
notifications:
  email: false
